apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsc-logs-ingestion
  namespace: airflow
  labels:
    app: logs-ingestion
    chain: bsc
  annotations:
    reloader.stakater.com/auto: "true"
    
spec:
  replicas: 1
  strategy:
    type: Recreate # 强制单实例 + 串行切换 （先 kill 旧 Pod，再建新 Pod
    #  kill old takes time and ingestion continus while the pod is in terminating status, ingestion paused for 1 sec only
  selector:
    matchLabels:
      app: logs-ingestion
      chain: bsc
  template:
    metadata:
      labels:
        app: logs-ingestion
        chain: bsc
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 1 # EOS is maintained by state topic
      containers:
        - name: ingestion
          image: web3-stream-ingestion:1.0.7
          imagePullPolicy: IfNotPresent
          command: ["python", "web3_realtime_logs.py"]

          # -----------------------------
          # Ingest runtime variables
          # -----------------------------
          env:
            - name: CHAIN
              value: "bsc"
            # -----------------------------
            # Parallel execution (BATCH_SIZE = MAX_WORKERS * RANGE_SIZE)
            # RANGE_SIZE <= 3 to reduce latency between checkping and chain_head
            # -----------------------------
            - name: RANGE_SIZE
              value: "5"

            - name: RPC_MAX_INFLIGHT
              value: "5"
      
            - name: RESUME_FROM_CHECKPOINT
              value: "true"
            
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          # -----------------------------
          # Metrics endpoint
          # -----------------------------
          ports:
            - name: metrics
              containerPort: 8000

          # -----------------------------
          # Environment variables
          # - Secrets only (API keys)
          # -----------------------------
          envFrom:
            - secretRef:
                name: rpc-api-keys

          # -----------------------------
          # Volume mount (RPC config)
          # -----------------------------
          volumeMounts:
            - name: rpc-config
              mountPath: /etc/ingestion
              readOnly: true

          # -----------------------------
          # (Optional but recommended)
          # Resource limits
          # -----------------------------
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   failureThreshold: 3

          # readinessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   failureThreshold: 3
          
          # startupProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          #   failureThreshold: 30
          #   periodSeconds: 5

      # -----------------------------
      # Volumes
      # -----------------------------
      volumes:
        - name: rpc-config
          configMap:
            name: blockchain-rpc-config
