apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-session
  namespace: flink
spec:
  image: flink-py:1.20.3-avro
  flinkVersion: v1_20
  serviceAccount: flink
  mode: standalone

  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "4"
    parallelism.default: "2"

    state.backend: rocksdb
    state.checkpoints.dir: file:///data/flink/checkpoints
    state.savepoints.dir: file:///data/flink/savepoints

    execution.checkpointing.interval: "30s"
    execution.checkpointing.mode: EXACTLY_ONCE

    kubernetes.operator.metrics.reporter.prom.enabled: "true"

  jobManager:
    resource:
      memory: "1024m"
      cpu: 1

  taskManager:
    resource:
      memory: "2048m"
      cpu: 2
    replicas: 2

  podTemplate:
    spec:
      securityContext:
        fsGroup: 9999
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-data
              mountPath: /data/flink
      volumes:
        - name: flink-data
          persistentVolumeClaim:
            claimName: flink-data-pvc
