apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-pyspark
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-pyspark
  template:
    metadata:
      labels:
        app: jupyter-pyspark
    spec:
      containers:
        - name: jupyter-pyspark
          image: jupyter-data-platform:0.1.6
          imagePullPolicy: IfNotPresent # use local customed image first
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: pyspark-notebook-data
              mountPath: /home/jovyan/work

          # -----------------------------
          # Environment variables
          # - Secrets only (API keys)
          # -----------------------------
          envFrom:
            - secretRef:
                name: bsc-rpc-secrets

      volumes:
        - name: pyspark-notebook-data
          persistentVolumeClaim:
            claimName: pvc-pyspark-notebook-data
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-pyspark
  namespace: airflow
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: jupyter-pyspark
