apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pyspark-notebook-data
  namespace: jupyter-pyspark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
