executor: "KubernetesExecutor"

dags:
  persistence:
    enabled: false

  gitSync:
    enabled: false

redis:
  enabled: false  # Celery backend not needed for KubernetesExecutor

postgresql:
  enabled: true

  image:
    repository: bitnamilegacy/postgresql
    tag: 16.1.0-debian-11-r15

  auth:
    enablePostgresUser: true
    username: "airflowuser"
    database: airflow
    existingSecret: airflow-postgresql-credentials

data:
  metadataConnection:
    user: airflowuser
    pass: airflow_db_password
    protocol: postgresql+psycopg2
    host: airflow-postgresql
    port: 5432
    db: airflow

triggerer:
  replicas: 1
  persistence:
    size: 5Gi

config:
  logging:
    remote_logging: "True"
    remote_base_log_folder: "s3://airflow-logs"
    remote_log_conn_id: "r2_conn"
    encrypt_s3_logs: "False"

# Passing logging config from ENV variables
env:
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: "s3://airflow-logs"
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: "r2_conn"
  - name: AIRFLOW__LOGGING__ENCRYPT_S3_LOGS
    value: "False"

# 从 secret 注入 R2 的 AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
extraEnvFromSecrets:
  - r2-credentials

  - name: AWS_ENDPOINT_URL
    value: "https://121187bd20a105c5426f6850e73960b8.r2.cloudflarestorage.com"  # R2 endpoint
  - name: AWS_DEFAULT_REGION
    value: "auto"  # R2 不需要具体 region

api:
  workers: 1
  timeout: 120
  host: 0.0.0.0
  port: 8080
  startupProbe:
    enabled: false
    httpGet:
      path: /api/v2/version
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 30
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

scheduler:
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  startupProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 60
    timeoutSeconds: 60