apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: airflow
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - services
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-jupyter-binding
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: default   # ← Jupyter pod 用的
    namespace: airflow
roleRef:
  kind: Role
  name: spark-driver-role
  apiGroup: rbac.authorization.k8s.io
