apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: brokers
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 3 # for production use at least 3 brokers
  roles:
    - broker

  storage:
    type: persistent-claim
    size: 10Gi
    class: standard

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
