{
 "title": "Multi-Chain Kafka Ingestion Overview",
 "tags": [
  "ingestion",
  "blockchain",
  "multi-chain"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(chain_latest_block, chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingestion Lag status (blocks)",
   "type": "stat",
   "description": "the gap between current checkpoint and chain head",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ingestion_checkpoint_lag{chain=~\"$chain\"})"
    }
   ]
  },
  {
   "title": "Ingestion Lag Over Time (blocks)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "ingestion_checkpoint_lag{chain=~\"$chain\"}",
     "legendFormat": "{{chain}} / {{job}}"
    }
   ]
  },
  {
   "title": "Total Logs Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\r\n  ingestion_tx_total{chain=~\"$chain\"}[30s]\r\n)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "RPC Errors / second (by provider)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(rpc_errors_total{chain=~\"$chain\"}[1m])",
     "legendFormat": "{{chain}} / {{rpc}}"
    }
   ]
  },
  {
   "title": "Transaction logs / second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "rate(ingestion_tx_total{chain=~\"$chain\"}[1m])",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "RPC Requests / second (by provider)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 10 },
   "repeat": "chain",
   "targets": [
    {
     "expr": "sum by (rpc) (rate(rpc_requests_total{chain=~\"$chain\"}[1m]))",
     "legendFormat": "{{rpc}}"
    }
   ]
  },
  {
   "title": "Blocks / second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "rate(ingestion_block_total{chain=~\"$chain\"}[1m])",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Pod Fatal Restarts (last 15m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    kube_pod_container_status_restarts_total{\r\n      namespace=\"airflow\",\r\n      container=~\".*logs-ingestion.*\"\r\n    }[15m]\r\n  )\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka Transaction Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kafka_transaction_failed_total{chain=~\"$chain\"}[15m])",
     "legendFormat": "{{chain}} / {{job}}"
    }
   ]
  },
  {
   "title": "Pod Fatal Restarts",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  namespace=\"airflow\",\r\n  container=~\".*logs-ingestion.*\",\r\n  reason=~\"Error|OOMKilled\"\r\n}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}