grafana:
  enabled: true

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

  grafana.ini:
    server:
      domain: smqj.cc
      root_url: https://smqj.cc/grafana/
      serve_from_sub_path: true

  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"

    hosts:
      - smqj.cc

    path: /grafana(/|$)(.*)
    pathType: ImplementationSpecific

prometheus:
  enabled: true

  service:
    type: ClusterIP
    port: 9090

  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"

    hosts:
      - smqj.cc

    paths:
      - /prometheus(/|$)(.*)

    pathType: ImplementationSpecific

  prometheusSpec:
    routePrefix: /
    externalUrl: https://smqj.cc/prometheus
    retention: 2d
    scrapeInterval: 30s

    resources:
      requests:
        cpu: 200m
        memory: 300Mi
      limits:
        cpu: 500m
        memory: 500Mi

alertmanager:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      memory: 50Mi
    limits:
      memory: 100Mi

prometheus-node-exporter:
  resources:
    requests:
      memory: 30Mi
    limits:
      memory: 50Mi