grafana:
  enabled: true

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

  grafana.ini:
    server:
      domain: smqj.cc
      root_url: https://smqj.cc/grafana/
      serve_from_sub_path: true

  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"

    hosts:
      - smqj.cc

    path: /grafana(/|$)(.*)

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"

    hosts:
      - smqj.cc

    paths:
      - /prometheus(/|$)(.*)

  prometheusSpec:
    routePrefix: /
    externalUrl: https://smqj.cc/prometheus
    retention: 2d

    resources:
      requests:
        memory: 300Mi
      limits:
        memory: 500Mi

alertmanager:
  enabled: false