# create role for KubernetesJobOperator
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-job-creator
  namespace: airflow
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
    
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-job-creator-binding
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-job-creator
  apiGroup: rbac.authorization.k8s.io
