apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-pod-operator
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-pod-operator-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: airflow-worker
  namespace: airflow
roleRef:
  kind: Role
  name: airflow-pod-operator
  apiGroup: rbac.authorization.k8s.io
