apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgresql-credentials
  namespace: airflow
type: Opaque
stringData:
  password: airflow_db_password
  postgres-password: postgres_password
  replication-password: replication_password