{
 "title": "Multi-Chain Kafka Ingestion Overview",
 "tags": [
  "ingestion",
  "blockchain",
  "multi-chain"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(chain_latest_block, chain)"
    }
   },
   {
    "name": "rpc",
    "query": {
     "query": "label_values(rpc_errors_total{chain=~\"$chain\"},rpc)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Blockchain and Ingestion Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Ingestion Lag status",
   "type": "stat",
   "description": "the gap between current checkpoint and chain head",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ingestion_checkpoint_lag{chain=~\"$chain\"})"
    }
   ]
  },
  {
   "title": "Ingestion Lag Over Time (blocks)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "ingestion_checkpoint_lag{chain=~\"$chain\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Processing logs / second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "rate(ingestion_tx_total{chain=~\"$chain\"}[1m])",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Total Logs Processed / pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ingestion_tx_total{chain=~\"$chain\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chain Head vs Ingestion Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "chain_latest_block{chain=~\"$chain\"}",
     "legendFormat": "chain_head"
    },
    {
     "expr": "ingestion_checkpoint{chain=~\"$chain\"}",
     "legendFormat": "checkpoint"
    }
   ]
  },
  {
   "title": "Blocks / second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "expr": "rate(ingestion_block_total{chain=~\"$chain\"}[1m])",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Log TX per Block (P50 / P95 / P99)",
   "type": "timeseries",
   "description": " | bucket | 意义        |\n| ------ | --------- |\n | p50    | median   |\n | p95    | busy blocks   |\n | p99    | extreme blocks |\n | p95/p99 | 表示 ingestion 在高负载区块下的压力边界 |",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ingestion_tx_per_block_bucket{chain=~\"$chain\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ingestion_tx_per_block_bucket{chain=\"$chain\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ingestion_tx_per_block_bucket{chain=\"$chain\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "RPC Reqs and Errors Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Commit inteveral seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(commit_interval_sec_latest{chain=~\"$chain\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Interval per Commit (P50 / P95 / P99)",
   "type": "timeseries",
   "description": "| bucket | 意义        |\n| ------ | --------- |\n | ≤1s    | 极快 / 理想   |\n | ≤2s    | 正常下限      |\n | ≤3s    | 正常        |\n | ≤5s    | 稳定(SLA p95) |\n | ≤8s    | 稍慢        |\n | ≤13s   | ⚠️ 明显变慢   |\n | ≤21s   | 🚨 接近不可接受 |\n | ≤34s   | 🔥 严重异常   |\n",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(commit_interval_sec_bucket{chain=~\"$chain\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(commit_interval_sec_bucket{chain=\"$chain\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(commit_interval_sec_bucket{chain=\"$chain\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Total RPC Reqs",
   "type": "stat",
   "description": "Cumulative reqs made across all RPC",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    increase(rpc_requests_total{chain=~\"$chain\"}[$__range])\r\n)",
     "legendFormat": "{{rpc}}"
    }
   ]
  },
  {
   "title": "RPC Reqs per Provider",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rpc_requests_total{chain=~\"$chain\"}[$__range])",
     "legendFormat": "{{rpc}}"
    }
   ]
  },
  {
   "title": "RPC Errors per Provider",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rpc_errors_total{chain=~\"$chain\"}[$__range])",
     "legendFormat": "{{rpc}}"
    }
   ]
  },
  {
   "title": "Total RPC Errors",
   "type": "stat",
   "description": "Cumulative errors made across all RPC",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    increase(rpc_errors_total{chain=~\"$chain\"}[$__range])\r\n)",
     "legendFormat": "{{rpc}}"
    }
   ]
  },
  {
   "title": "RPC Error Rates by Provider",
   "type": "timeseries",
   "description": "error rate = rpc_errors_total / rpc_requests_total (by date range)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase (\r\n  rpc_errors_total{chain=~\"$chain\"}[$__range]\r\n)\r\n/\r\n  increase (\r\n    rpc_requests_total{chain=~\"$chain\"}[$__range]\r\n  )",
     "legendFormat": "{{rpc}}"
    }
   ]
  },
  {
   "title": "RPC Errors by key_env",
   "type": "timeseries",
   "description": "判断哪个 API key 出问题",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (key_env) (\r\n  increase(\r\n    rpc_errors_total{\r\n      chain=~\"$chain\",\r\n      rpc=~\"$rpc\"\r\n    }[$__range]\r\n  )\r\n)",
     "legendFormat": "{{key_env}}"
    }
   ]
  }
 ]
}