apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: analytics-ch
  namespace: clickhouse
spec:
  defaults:
    templates:
      podTemplate: ch-pod

  configuration:
    clusters:
      - name: analytics
        layout:
          shardsCount: 1 # add shards for data distribution and scalability
          replicasCount: 1  # add replicas for high availability and fault tolerance

    users:
        metabase/password: metabase_password  # create user 'metabase' for Metabase access
        metabase/profile: default
        metabase/quota: default
        metabase/networks/ip:
          - 0.0.0.0/0 # allow access from any IP (adjust for security as needed)

  templates:
    podTemplates:
      - name: ch-pod
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.3
              resources:
                requests:
                  cpu: "1"
                  memory: "2Gi"
                limits:
                  cpu: "4"
                  memory: "8Gi"

    volumeClaimTemplates:
      - name: ch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 50Gi