apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: erigon-bsc
  namespace: prometheus
  labels:
    release: prometheus        # service discovery for prometheus
spec:
  selector:
    matchLabels:
      app: erigon-bsc
  namespaceSelector:
    matchNames:
      - blockchain
  endpoints:
    - port: metrics
      interval: 15s
