apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: erigon-bsc
  namespace: blockchain
spec:
  serviceName: erigon-bsc
  replicas: 1
  selector:
    matchLabels:
      app: erigon-bsc
  template:
    metadata:
      labels:
        app: erigon-bsc
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: erigon
          image: erigontech/erigon:main-9cb3a83
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/config/erigon.sh"]
          
          ports:
            - name: http
              containerPort: 8545
            - name: metrics
              containerPort: 6060
          # resources:
          #   requests:
          #     cpu: "8"
          #     memory: "32Gi"
          #   limits:
          #     cpu: "16"
          #     memory: "64Gi"
          volumeMounts:
            - name: data
              mountPath: /data/erigon
            - name: config
              mountPath: /config
          readinessProbe:
            httpGet:
              path: /
              port: 8545
            initialDelaySeconds: 120
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: erigon-bsc-config
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Ti
